### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by xYundy** [ttuples/SimpleCaptcha#2]
Hey! Very nice mod! 😃 

I would be even better if there is a way to make translations for it..

If you make support for language files I would love to help you with translations 😄

**Comment by ttuples** [comment]
Yes! I will get to work on that right away and inform you when I have it implemented.

**Comment by ttuples** [comment]
@xYundy I have just updated the repository with the new language file support code.
Thank you for offering to add translations! 😄

**Comment by xYundy** [comment]
Thank you very much!
